export const MODAL_OPEN = 'MODAL_OPEN'
export const MODAL_CLOSE = 'MODAL_CLOSE'
export const PROFILE_OPEN = 'PROFILE_OPEN'
export const PROFILE_CLOSE = 'PROFILE_CLOSE'
export const MENU_OPEN = 'MENU_OPEN'
export const MENU_CLOSE = 'MENU_CLOSE'
