export const CREATE_TWEET = 'CREATE_TWEET'
export const LIKE_TWEET = 'LIKE_TWEET'
export const UNLIKE_TWEET = 'UNLIKE_TWEET'
export const RETWEET = 'RETWEET'
export const UNRETWEET = 'UNRETWEET'
export const REPLY = 'REPLY'
